# Generated by Django 5.1.7 on 2025-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_rename_designation_produit_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
